apiVersion: v1
kind: ConfigMap
metadata:
  name: service-urls
  namespace: microservices-demo
data:
  INVENTORY_SERVICE_URL: http://inventory-service:8081
  ORDER_SERVICE_URL: http://order-service:8082
