server.port=8082
spring.application.name=order-service

spring.datasource.url=jdbc:h2:mem:orderdb
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update

# Overridden by docker-compose / k8s env var to point at the inventory-service container/pod
inventory.service.url=${INVENTORY_SERVICE_URL:http://localhost:8081}

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
